### ISSUE TITLE
Ability to insert manual redirects to species pages.

### ISSUE THREAD

**Issue by Sherrin-ALA** [AtlasOfLivingAustralia/ala-bie-hub#74]
It would be useful if there was a way of manually adding redirects to species pages. For example :https://bie.ala.org.au/species/Chamaecrista%20mimosoides  
is not longer a valid URL, even though _Chamaecrista mimosoides_ is still a valid name https://bie.ala.org.au/species/https://id.biodiversity.org.au/node/apni/2916908

(Freshdesk request - https://support.ehelp.edu.au/a/tickets/181922)

**Comment by adam-collins** [comment]
What is producing this invalid URL? Fixing this invalid URL is preferred.

Synonym entries the names index perform this function and can be used. This is achieved by creating a valid names index DwCA for importing into the BIE. There is a directory on the bie-index server and an admin UI that can be used to import additional DwCA's that may contain new synonym entries. 
- Provides a new DwCA that can be reused when building the next names index so this is not wasted effort.
- No additional functionality or UI is required.
- This will produce inconsistencies between BIE and name-matching-service that will remain until a new index is released.
- Does require access to the server to upload the additional DwCA.

I prefer this not to take place because:
- Name matching should be consistent across the ALA.
- Faster turnaround for changes to the names index used in the BIE and name matching services is preferable to a half measure in the BIE.

**Comment by Sherrin-ALA** [comment]
Makes sense - will close this issue
