### ISSUE TITLE
Remove irrelevant wikipedia disambiguation links from BIE page

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/ala-bie-hub#89]
Eg https://bie.ala.org.au/species/NZOR-6-48824 (Chara) can refer to an algae, a moth, several people, several places etc.

<img width="894" alt="image" src="https://github.com/AtlasOfLivingAustralia/ala-bie-hub/assets/4031353/84b350b0-ac71-468e-8fa2-278f30b5acc9">

**Comment by javier-molina** [comment]
My take is this family is an algae, Adam has helped me so point it to https://en.wikipedia.org/wiki/Chara_(alga)

**Comment by TaniaGLaity** [comment]
I have checked - and closed

**Comment by nickdos** [comment]
Re-opening this issue, as it is closely matches a more recent problem where incorrect Wikipedia pages are still being linked to BIE species pages. The suggested fix is to add a check/query to the initial request to Wikipedia, so it only returns pages that have a “Scientific Classification” entity (tag?) present. 

Requires first checking at least 10 prominent species pages with Wikipedia entries to confirm they do have this entity/tag.

**Comment by peggynewman** [comment]
Taxonomy WG has done a lot of preliminary analysis on this. I'd recommend checking back with them

**Comment by Sherrin-ALA** [comment]
### Notes from Taxonomy Analysis
### Direct checking of Wikipedia Articles.
Articles in Wikipedia that are about biological organisms contain a side bar that displays taxonomic information. There appear to be two types - one for species and one for higher classifications. Both contain the text “Scientific Classification” 
https://en.wikipedia.org/wiki/Vertebrate
https://en.wikipedia.org/wiki/Moggridgea_rainbowi

In the “raw” version of those pages, the presence of either the “taxobox” or “Speciesbox” components can be used to determine  that the pages is about a biological organism. In both cases the scientific name is in the “taxon” property for that component.
      https://en.wikipedia.org/w/index.php?title=vertebrate&action=raw
      https://en.wikipedia.org/w/index.php?title=Moggridgea%20rainbowi&action=raw
      

**Known limitations of this approach:**

Homonyms: 
The “raw” version of the Wikipedia content does not contain higher taxonomic information, so it’s not possible to confirm that the content is for the required taxon (for example - Vetebrata is a type of Algae but the content on that page was for the subphylum in Animalia). The full version of a Wikipedia page does contain the taxonomic hierarchy but parsing out data may not be straight forward. The full higher taxonomy in Wikipedia may not match the ALA higher taxonomy, but checking against Kingdom will avoid cross kingdom homonyms.

Missed entries: 
More likely to occur with higher order taxonomy than at a species level, but potential entries may be missed. This is preferable to displaying inappropriate information.

### Using  Wikidata queries.

Using Wikidata to find taxonomic entries and associated Wikipedia pages has the potential to return more results and allow for homonym checking. 
For example, this verbose query 
      [https://w.wiki/Sc54](https://w.wiki/Sc54)
will return a matching taxon entry with its associate Wikipedia page (if it exists) along with the higher taxonomy. Having the higher taxonomy allows for checking of homonyms.

**Known limitations of this approach:**

Rate limitations:
 Queries to Wikidata are rate limited in terms of number of queries per minute and processing time.  Searching every accepted taxon name may take an impractical amount of time. Other approaches such as using a query all the children of a particular genus, and then matching the species and subspecies returned to entries for that genus in the ALA taxonomy may be more efficient use of Wikidata queries. For example this query returns all the entries for taxa that have a parent of Lepidoptera (Moths and Butterflies) that are marked as being endemic to Australia (which may be over-limiting)
[https://w.wiki/Sc5m](https://w.wiki/Sc5m)
This query returns the taxa that have an parent of Osphranter
[https://w.wiki/Sc5t](https://w.wiki/Sc5t)

**Comment by nickdos** [comment]
Most issues have been address but experimenting with Wikidata API, it is far too slow to be useable in this application and current changes seem good enough for now. 

<img width="691" height="324" alt="Image" src="https://github.com/user-attachments/assets/8068371a-cb85-4733-908d-4cd98788d96c" />

**Comment by nickdos** [comment]
Summary of changes made for this issue.

- previously the species page code called the wikipedia "page" API, and assumed there was a Wikipedia page with the same "text" as the species page "accepted name" as it's title. This assumption was incorrect, as there were some pages where a taxon name matched multiple pages. 
-  instead, the code now calls the Wikipedia "search" API using the accepted name (with any subgenus stripped out, as Wikipedia does not include subgenus). If multiple pages are returned, each entry is checked (via the "snippet" description text in the JSON results) by looking for [commonly used terms](https://github.com/AtlasOfLivingAustralia/ala-bie-hub/blob/develop/grails-app/conf/application.yml#L230) found on taxon pages (configurable, so can be modified later via config file), otherwise if a single result, it is used.
- The "page" API is called with the page title obtained via "search" and this is then "checked" to see it contains a "taxabox" section that is common to all taxon pages, as it shows the higher taxa names. Thus, a second filter is applied. If no "taxabox" section is found, no Wikipedia content is included.
- Unit tests were added to the code, as well as an integration test that calls the Wikipedia API using a CSV list. The latter is not run on builds, as the reliance on Wikipedia API could break builds when the service is slow or if we get rate limited. The integration test is run weekly via a separate [Github Action](https://github.com/AtlasOfLivingAustralia/ala-bie-hub/actions/workflows/live-wikipedia-check.yml) that sends a notification if it fails.
- The integration test uses the [ALA iconic species list](https://lists.ala.org.au/list/dr781) as a [source of names](https://github.com/AtlasOfLivingAustralia/ala-bie-hub/blob/develop/src/liveWikipediaTest/resources/wikipedia-live-tests.csv) and has only 1 out of the 145 entries for the CSV file that does not match a Wikipedia article.
- Adding the ability to strip the subgenus from the accepted name, fixed an issue where many vertebrate species had no Wikipedia content, so this fix should improve descriptive content in the BIE.

**Comment by nickdos** [comment]
Following more testing of these changes (thanks @Sherrin-ALA) it was agreed to make a minor improvement to the way manual overrides are handled. Currently the `wikiUrl` value that an admin provided as an override, is stripped back to the "page title" and then passed to the wikipedia controller as `/externalSite/wikipedia?name={title}&kingdom={kingdom}`. The problem with this approach is, the wikipedia service has no way of distinguishing a "page title" from a "regular taxon name", so has to treat them the same way (and thus performs the checks I added in this change set). This can result in the page not displaying content, due to (say) the kingdom not matching. This is a problem for Algae species pages, as Wikipedia is avoiding the kingdom debate (is it a plant or fungi) but not including any kingdom designation at all. This results in kingdom check failing and no content is returned. So even the overrides fail to display.

The suggested fix is to modify the `/externalSite/wikipedia` endpoint to accept an additional param called  "url" (or "wikiUrl"), and if present, simply load the page for that URL (with sanitation filters).
